export const SET_COUNTRYNAME = "SET_COUNTRYNAME";
export const SET_COUNTRY_FLAG = "SET_COUNTRY_FLAG";
export const SET_COUNTRY_DETAILS = "SET_COUNTRY_DETAILS";
export const TOGGLE_ERROR = "TOGGLE_ERROR";